plugins {
    id 'net.fabricmc.fabric-loom' version '1.15.+'
    id 'maven-publish'
}

version = '1.0.0'
group = 'com.backmod'
base { archivesName = 'backmod' }

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
    withSourcesJar()
}

repositories {
    maven { url 'https://maven.fabricmc.net/' }
}

dependencies {
    minecraft "com.mojang:minecraft:26.1.2"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:0.18.4"
    modImplementation "net.fabricmc.fabric-api:fabric-api:0.150.0+26.1.2"
}

processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') {
        expand version: project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 25
}

jar {
    from('LICENSE') { rename { "${it}_${project.base.archivesName.get()}" } }
}
